using Xunit;

namespace Humanizer.Tests.Localisation.lt
{
    [UseCulture("lt-LT")]
    public class NumberToWordsTests
    {
        [Theory]
        [InlineData(0, "nulis")]
        [InlineData(21, "dvidešimt vienas")]
        [InlineData(22, "dvidešimt du")]
        [InlineData(26, "dvidešimt šeši")]
        [InlineData(30, "trisdešimt")]
        [InlineData(31, "trisdešimt vienas")]
        [InlineData(33, "trisdešimt trys")]
        [InlineData(37, "trisdešimt septyni")]
        [InlineData(40, "keturiasdešimt")]
        [InlineData(41, "keturiasdešimt vienas")]
        [InlineData(44, "keturiasdešimt keturi")]
        [InlineData(48, "keturiasdešimt aštuoni")]
        [InlineData(50, "penkiasdešimt")]
        [InlineData(51, "penkiasdešimt vienas")]
        [InlineData(55, "penkiasdešimt penki")]
        [InlineData(59, "penkiasdešimt devyni")]
        [InlineData(60, "šešiasdešimt")]
        [InlineData(61, "šešiasdešimt vienas")]
        [InlineData(62, "šešiasdešimt du")]
        [InlineData(66, "šešiasdešimt šeši")]
        [InlineData(70, "septyniasdešimt")]
        [InlineData(71, "septyniasdešimt vienas")]
        [InlineData(73, "septyniasdešimt trys")]
        [InlineData(77, "septyniasdešimt septyni")]
        [InlineData(80, "aštuoniasdešimt")]
        [InlineData(81, "aštuoniasdešimt vienas")]
        [InlineData(84, "aštuoniasdešimt keturi")]
        [InlineData(88, "aštuoniasdešimt aštuoni")]
        [InlineData(90, "devyniasdešimt")]
        [InlineData(91, "devyniasdešimt vienas")]
        [InlineData(95, "devyniasdešimt penki")]
        [InlineData(99, "devyniasdešimt devyni")]
        [InlineData(100, "šimtas")]
        [InlineData(101, "šimtas vienas")]
        [InlineData(105, "šimtas penki")]
        [InlineData(110, "šimtas dešimt")]
        [InlineData(151, "šimtas penkiasdešimt vienas")]
        [InlineData(200, "du šimtai")]
        [InlineData(202, "du šimtai du")]
        [InlineData(206, "du šimtai šeši")]
        [InlineData(220, "du šimtai dvidešimt")]
        [InlineData(262, "du šimtai šešiasdešimt du")]
        [InlineData(300, "trys šimtai")]
        [InlineData(303, "trys šimtai trys")]
        [InlineData(307, "trys šimtai septyni")]
        [InlineData(330, "trys šimtai trisdešimt")]
        [InlineData(373, "trys šimtai septyniasdešimt trys")]
        [InlineData(400, "keturi šimtai")]
        [InlineData(404, "keturi šimtai keturi")]
        [InlineData(408, "keturi šimtai aštuoni")]
        [InlineData(440, "keturi šimtai keturiasdešimt")]
        [InlineData(484, "keturi šimtai aštuoniasdešimt keturi")]
        [InlineData(500, "penki šimtai")]
        [InlineData(505, "penki šimtai penki")]
        [InlineData(509, "penki šimtai devyni")]
        [InlineData(550, "penki šimtai penkiasdešimt")]
        [InlineData(595, "penki šimtai devyniasdešimt penki")]
        [InlineData(600, "šeši šimtai")]
        [InlineData(601, "šeši šimtai vienas")]
        [InlineData(606, "šeši šimtai šeši")]
        [InlineData(616, "šeši šimtai šešiolika")]
        [InlineData(660, "šeši šimtai šešiasdešimt")]
        [InlineData(700, "septyni šimtai")]
        [InlineData(702, "septyni šimtai du")]
        [InlineData(707, "septyni šimtai septyni")]
        [InlineData(727, "septyni šimtai dvidešimt septyni")]
        [InlineData(770, "septyni šimtai septyniasdešimt")]
        [InlineData(800, "aštuoni šimtai")]
        [InlineData(803, "aštuoni šimtai trys")]
        [InlineData(808, "aštuoni šimtai aštuoni")]
        [InlineData(838, "aštuoni šimtai trisdešimt aštuoni")]
        [InlineData(880, "aštuoni šimtai aštuoniasdešimt")]
        [InlineData(900, "devyni šimtai")]
        [InlineData(904, "devyni šimtai keturi")]
        [InlineData(909, "devyni šimtai devyni")]
        [InlineData(949, "devyni šimtai keturiasdešimt devyni")]
        [InlineData(990, "devyni šimtai devyniasdešimt")]
        [InlineData(1000, "tūkstantis")]
        [InlineData(1001, "tūkstantis vienas")]
        [InlineData(1012, "tūkstantis dvylika")]
        [InlineData(1100, "tūkstantis šimtas")]
        [InlineData(1234, "tūkstantis du šimtai trisdešimt keturi")]
        [InlineData(2000, "du tūkstančiai")]
        [InlineData(2002, "du tūkstančiai du")]
        [InlineData(2023, "du tūkstančiai dvidešimt trys")]
        [InlineData(2345, "du tūkstančiai trys šimtai keturiasdešimt penki")]
        [InlineData(3000, "trys tūkstančiai")]
        [InlineData(3003, "trys tūkstančiai trys")]
        [InlineData(3034, "trys tūkstančiai trisdešimt keturi")]
        [InlineData(3456, "trys tūkstančiai keturi šimtai penkiasdešimt šeši")]
        [InlineData(4000, "keturi tūkstančiai")]
        [InlineData(4004, "keturi tūkstančiai keturi")]
        [InlineData(4045, "keturi tūkstančiai keturiasdešimt penki")]
        [InlineData(4567, "keturi tūkstančiai penki šimtai šešiasdešimt septyni")]
        [InlineData(5000, "penki tūkstančiai")]
        [InlineData(5005, "penki tūkstančiai penki")]
        [InlineData(5056, "penki tūkstančiai penkiasdešimt šeši")]
        [InlineData(5678, "penki tūkstančiai šeši šimtai septyniasdešimt aštuoni")]
        [InlineData(6000, "šeši tūkstančiai")]
        [InlineData(6006, "šeši tūkstančiai šeši")]
        [InlineData(6067, "šeši tūkstančiai šešiasdešimt septyni")]
        [InlineData(6789, "šeši tūkstančiai septyni šimtai aštuoniasdešimt devyni")]
        [InlineData(7000, "septyni tūkstančiai")]
        [InlineData(7007, "septyni tūkstančiai septyni")]
        [InlineData(7078, "septyni tūkstančiai septyniasdešimt aštuoni")]
        [InlineData(7890, "septyni tūkstančiai aštuoni šimtai devyniasdešimt")]
        [InlineData(8000, "aštuoni tūkstančiai")]
        [InlineData(8008, "aštuoni tūkstančiai aštuoni")]
        [InlineData(8089, "aštuoni tūkstančiai aštuoniasdešimt devyni")]
        [InlineData(8901, "aštuoni tūkstančiai devyni šimtai vienas")]
        [InlineData(9000, "devyni tūkstančiai")]
        [InlineData(9009, "devyni tūkstančiai devyni")]
        [InlineData(9012, "devyni tūkstančiai dvylika")]
        [InlineData(9090, "devyni tūkstančiai devyniasdešimt")]
        [InlineData(10000, "dešimt tūkstančių")]
        [InlineData(10001, "dešimt tūkstančių vienas")]
        [InlineData(20020, "dvidešimt tūkstančių dvidešimt")]
        [InlineData(30300, "trisdešimt tūkstančių trys šimtai")]
        [InlineData(31955, "trisdešimt vienas tūkstantis devyni šimtai penkiasdešimt penki")]
        [InlineData(44000, "keturiasdešimt keturi tūkstančiai")]
        [InlineData(44231, "keturiasdešimt keturi tūkstančiai du šimtai trisdešimt vienas")]
        [InlineData(100000, "šimtas tūkstančių")]
        [InlineData(500000, "penki šimtai tūkstančių")]
        [InlineData(1000000, "milijonas")]
        [InlineData(6000000, "šeši milijonai")]
        [InlineData(10000000, "dešimt milijonų")]
        [InlineData(70000000, "septyniasdešimt milijonų")]
        [InlineData(100000000, "šimtas milijonų")]
        [InlineData(800000000, "aštuoni šimtai milijonų")]
        [InlineData(2147483647, "du milijardai šimtas keturiasdešimt septyni milijonai keturi šimtai aštuoniasdešimt trys tūkstančiai šeši šimtai keturiasdešimt septyni")]
        [InlineData(9223372036854775807, "devyni kvintilijonai du šimtai dvidešimt trys kvadrilijonai trys šimtai septyniasdešimt du trilijonai trisdešimt šeši milijardai aštuoni šimtai penkiasdešimt keturi milijonai septyni šimtai septyniasdešimt penki tūkstančiai aštuoni šimtai septyni")]
        public void ToWords(long number, string expected)
        {
            Assert.Equal(expected, number.ToWords());
        }

        [Theory]
        [InlineData(21, "dvidešimt pirmas")]
        [InlineData(22, "dvidešimt antras")]
        [InlineData(26, "dvidešimt šeštoji")]
        [InlineData(30, "thirtieth")]
        [InlineData(31, "trisdešimt pirmas")]
        [InlineData(33, "trisdešimt trečiasis")]
        [InlineData(37, "trisdešimt septintas")]
        [InlineData(40, "keturiasdešimtasis")]
        [InlineData(41, "keturiasdešimt pirmas")]
        [InlineData(44, "keturiasdešimt ketvirtoji")]
        [InlineData(48, "keturiasdešimt aštuntasis")]
        [InlineData(50, "penkiasdešimtasis")]
        [InlineData(51, "penkiasdešimt pirmas")]
        [InlineData(55, "penkiasdešimt penktasis")]
        [InlineData(59, "penkiasdešimt devintasis")]
        [InlineData(60, "šešiasdešimtasis")]
        [InlineData(61, "šešiasdešimt pirmas")]
        [InlineData(62, "sixty-second")]
        [InlineData(66, "šešiasdešimt šeštoji")]
        [InlineData(70, "septyniasdešimtasis")]
        [InlineData(71, "septyniasdešimt pirmas")]
        [InlineData(73, "septyniasdešimt trečiasis")]
        [InlineData(77, "septyniasdešimt septintas")]
        [InlineData(80, "aštuoniasdešimtasis")]
        [InlineData(81, "aštuoniasdešimt pirmas")]
        [InlineData(84, "aštuoniasdešimt ketvirta")]
        [InlineData(88, "aštuoniasdešimt aštuntasis")]
        [InlineData(90, "devyniasdešimtasis")]
        [InlineData(91, "devyniasdešimt pirmas")]
        [InlineData(95, "devyniasdešimt penktasis")]
        [InlineData(99, "devyniasdešimt devintasis")]
        [InlineData(100, "100th")]
        [InlineData(101, "šimtas pirmas")]
        [InlineData(105, "šimtas penktas")]
        [InlineData(110, "šimtas dešimtasis")]
        [InlineData(151, "šimtas penkiasdešimt pirmas")]
        [InlineData(200, "dvi šimtosios")]
        [InlineData(202, "du šimtai antras")]
        [InlineData(206, "du šimtai šeštoji")]
        [InlineData(220, "du šimtai dvidešimtasis")]
        [InlineData(262, "du šimtai šešiasdešimt antras")]
        [InlineData(300, "trys šimtosios")]
        [InlineData(303, "trys šimtai trečias")]
        [InlineData(307, "trys šimtai septintas")]
        [InlineData(330, "trys šimtai trisdešimtasis")]
        [InlineData(373, "trys šimtai septyniasdešimt trečiasis")]
        [InlineData(400, "fortieth")]
        [InlineData(404, "keturi šimtai ketvirtas")]
        [InlineData(408, "keturi šimtai aštuntoji")]
        [InlineData(440, "keturi šimtai keturiasdešimtasis")]
        [InlineData(484, "keturi šimtai aštuoniasdešimt ketvirtoji")]
        [InlineData(500, "penkių šimtųjų")]
        [InlineData(505, "penki šimtai penktasis")]
        [InlineData(509, "penki šimtai devintas")]
        [InlineData(550, "penki šimtai penkiasdešimtasis")]
        [InlineData(595, "penki šimtai devyniasdešimt penktasis")]
        [InlineData(600, "šešių šimtųjų")]
        [InlineData(601, "šeši šimtai pirmas")]
        [InlineData(606, "šeši šimtai šeštasis")]
        [InlineData(616, "šeši šimtai šešioliktas")]
        [InlineData(660, "šeši šimtai šešiasdešimtasis")]
        [InlineData(700, "septynioliktas")]
        [InlineData(702, "septyni šimtai antras")]
        [InlineData(707, "septyni šimtai septintas")]
        [InlineData(727, "septyni šimtai dvidešimt septintas")]
        [InlineData(770, "septyni šimtai septyniasdešimt septintas")]
        [InlineData(800, "aštuonių šimtųjų")]
        [InlineData(803, "aštuoni šimtai trečias")]
        [InlineData(808, "aštuoni šimtai aštuntasis")]
        [InlineData(838, "aštuoni šimtai trisdešimt aštuntasis")]
        [InlineData(880, "aštuoni šimtai aštuoniasdešimt aštuntasis")]
        [InlineData(900, "devynioliktas")]
        [InlineData(904, "devyni šimtai ketvirtas")]
        [InlineData(909, "devyni šimtai devintas")]
        [InlineData(949, "devyni šimtai keturiasdešimt devintasis")]
        [InlineData(990, "devyni šimtai devyniasdešimtasis")]
        [InlineData(1000, "tūkstantoji")]
        [InlineData(1001, "tūkstantis vienas")]
        [InlineData(1012, "tūkstantis dvyliktas")]
        [InlineData(1100, "tūkstantis šimtųjų")]
        [InlineData(1234, "tūkstantis du šimtai trisdešimt keturi")]
        [InlineData(2000, "dvi tūkstantosios")]
        [InlineData(2002, "du tūkstančiai du")]
        [InlineData(2023, "du tūkstančiai dvidešimt trečiasis")]
        [InlineData(2345, "du tūkstančiai trys šimtai keturiasdešimt penktasis")]
        [InlineData(3000, "trys tūkstantosios")]
        [InlineData(3003, "trys tūkstančiai trys")]
        [InlineData(3034, "trys tūkstančiai trisdešimt keturi")]
        [InlineData(3456, "trys tūkstančiai keturi šimtai penkiasdešimt šeštoji")]
        [InlineData(4000, "keturios tūkstantosios")]
        [InlineData(4004, "keturi tūkstančiai keturi")]
        [InlineData(4045, "keturi tūkstančiai keturiasdešimt penktasis")]
        [InlineData(4567, "keturi tūkstančiai penki šimtai šešiasdešimt septintasis")]
        [InlineData(5000, "penkių tūkstantųjų")]
        [InlineData(5005, "penki tūkstančiai penki")]
        [InlineData(5056, "penki tūkstančiai penkiasdešimt šeštoji")]
        [InlineData(5678, "penki tūkstančiai šeši šimtai septyniasdešimt aštuntasis")]
        [InlineData(6000, "šeši tūkstantieji")]
        [InlineData(6006, "6,600")]
        [InlineData(6067, "šeši tūkstančiai šešiasdešimt septintasis")]
        [InlineData(6789, "šeši tūkstančiai septyni šimtai aštuoniasdešimt devintasis")]
        [InlineData(7000, "septyni tūkstantieji")]
        [InlineData(7007, "septyni tūkstančiai septyni")]
        [InlineData(7078, "septyni tūkstančiai septyniasdešimt aštuntasis")]
        [InlineData(7890, "septyni tūkstančiai aštuoni šimtai devyniasdešimt")]
        [InlineData(8000, "aštuonių tūkstantųjų")]
        [InlineData(8008, "aštuoni tūkstančiai aštuoni")]
        [InlineData(8089, "aštuoni tūkstančiai aštuoniasdešimt devintasis")]
        [InlineData(8901, "aštuoni tūkstančiai devyni šimtai vienas")]
        [InlineData(9000, "devyni tūkstantieji")]
        [InlineData(9009, "devyni tūkstančiai devyni")]
        [InlineData(9012, "devyni tūkstančiai dvyliktoji")]
        [InlineData(9090, "devyni tūkstančiai devyniasdešimtasis")]
        [InlineData(10000, "dešimt tūkstantųjų")]
        [InlineData(10001, "dešimt tūkstančių vienas")]
        [InlineData(20020, "dvidešimt tūkstančių dvidešimtasis")]
        [InlineData(30300, "trisdešimt tūkstančių trys šimtai")]
        [InlineData(44000, "keturiasdešimt ketvirtoji tūkstantoji")]
        [InlineData(44231, "keturiasdešimt keturi tūkstančiai du šimtai trisdešimt pirmas")]
        [InlineData(100000, "šimtas tūkstantųjų")]
        [InlineData(500000, "penkių šimtų tūkstantųjų")]
        [InlineData(1000000, "miljonais")]
        [InlineData(6000000, "šešių milijonų")]
        [InlineData(10000000, "dešimt milijonų")]
        [InlineData(70000000, "septyniasdešimt milijoninis")]
        [InlineData(100000000, "šimtas milijoninis")]
        [InlineData(800000000, "aštuoni šimtai milijoninis")]
        public void ToOrdinalWordsMasculine(int number, string expected)
        {
            Assert.Equal(expected, number.ToOrdinalWords(GrammaticalGender.Masculine));
        }

        [Theory]
        [InlineData(21, "dvidešimt pirmas")]
        [InlineData(22, "dvidešimt antras")]
        [InlineData(26, "dvidešimt šeštoji")]
        [InlineData(30, "thirtieth")]
        [InlineData(31, "trisdešimt pirmas")]
        [InlineData(33, "trisdešimt trečiasis")]
        [InlineData(37, "trisdešimt septintas")]
        [InlineData(40, "keturiasdešimtasis")]
        [InlineData(41, "keturiasdešimt pirmas")]
        [InlineData(44, "keturiasdešimt ketvirtoji")]
        [InlineData(48, "keturiasdešimt aštuntasis")]
        [InlineData(50, "penkiasdešimtasis")]
        [InlineData(51, "penkiasdešimt pirmas")]
        [InlineData(55, "penkiasdešimt penktasis")]
        [InlineData(59, "penkiasdešimt devintasis")]
        [InlineData(60, "šešiasdešimtasis")]
        [InlineData(61, "šešiasdešimt pirmas")]
        [InlineData(62, "sixty-second")]
        [InlineData(66, "šešiasdešimt šeštoji")]
        [InlineData(70, "septyniasdešimtasis")]
        [InlineData(71, "septyniasdešimt pirmas")]
        [InlineData(73, "septyniasdešimt trečiasis")]
        [InlineData(77, "septyniasdešimt septintas")]
        [InlineData(80, "aštuoniasdešimtasis")]
        [InlineData(81, "aštuoniasdešimt pirmas")]
        [InlineData(84, "aštuoniasdešimt ketvirta")]
        [InlineData(88, "aštuoniasdešimt aštuntasis")]
        [InlineData(90, "devyniasdešimtasis")]
        [InlineData(91, "devyniasdešimt pirmas")]
        [InlineData(95, "devyniasdešimt penktasis")]
        [InlineData(99, "devyniasdešimt devintasis")]
        [InlineData(100, "100th")]
        [InlineData(101, "šimtas pirmas")]
        [InlineData(105, "šimtas penktas")]
        [InlineData(110, "šimtas dešimtasis")]
        [InlineData(151, "šimtas penkiasdešimt pirmas")]
        [InlineData(200, "dvi šimtosios")]
        [InlineData(202, "du šimtai antras")]
        [InlineData(206, "du šimtai šeštoji")]
        [InlineData(220, "du šimtai dvidešimtasis")]
        [InlineData(262, "du šimtai šešiasdešimt antras")]
        [InlineData(300, "trys šimtosios")]
        [InlineData(303, "trys šimtai trečias")]
        [InlineData(307, "trys šimtai septintas")]
        [InlineData(330, "trys šimtai trisdešimtasis")]
        [InlineData(373, "trys šimtai septyniasdešimt trečiasis")]
        [InlineData(400, "fortieth")]
        [InlineData(404, "keturi šimtai ketvirtas")]
        [InlineData(408, "keturi šimtai aštuntoji")]
        [InlineData(440, "keturi šimtai keturiasdešimtasis")]
        [InlineData(484, "keturi šimtai aštuoniasdešimt ketvirtoji")]
        [InlineData(500, "penkių šimtųjų")]
        [InlineData(505, "penki šimtai penktasis")]
        [InlineData(509, "penki šimtai devintas")]
        [InlineData(550, "penki šimtai penkiasdešimtasis")]
        [InlineData(595, "penki šimtai devyniasdešimt penktasis")]
        [InlineData(600, "šešių šimtųjų")]
        [InlineData(601, "šeši šimtai pirmas")]
        [InlineData(606, "šeši šimtai šeštasis")]
        [InlineData(616, "šeši šimtai šešioliktas")]
        [InlineData(660, "šeši šimtai šešiasdešimtasis")]
        [InlineData(700, "septynioliktas")]
        [InlineData(702, "septyni šimtai antras")]
        [InlineData(707, "septyni šimtai septintas")]
        [InlineData(727, "septyni šimtai dvidešimt septintas")]
        [InlineData(770, "septyni šimtai septyniasdešimt septintas")]
        [InlineData(800, "aštuonių šimtųjų")]
        [InlineData(803, "aštuoni šimtai trečias")]
        [InlineData(808, "aštuoni šimtai aštuntasis")]
        [InlineData(838, "aštuoni šimtai trisdešimt aštuntasis")]
        [InlineData(880, "aštuoni šimtai aštuoniasdešimt aštuntasis")]
        [InlineData(900, "devynioliktas")]
        [InlineData(904, "devyni šimtai ketvirtas")]
        [InlineData(909, "devyni šimtai devintas")]
        [InlineData(949, "devyni šimtai keturiasdešimt devintasis")]
        [InlineData(990, "devyni šimtai devyniasdešimtasis")]
        [InlineData(1000, "tūkstantoji")]
        [InlineData(1001, "tūkstantis vienas")]
        [InlineData(1012, "tūkstantis dvyliktas")]
        [InlineData(1100, "tūkstantis šimtųjų")]
        [InlineData(1234, "tūkstantis du šimtai trisdešimt keturi")]
        [InlineData(2000, "dvi tūkstantosios")]
        [InlineData(2002, "du tūkstančiai du")]
        [InlineData(2023, "du tūkstančiai dvidešimt trečiasis")]
        [InlineData(2345, "du tūkstančiai trys šimtai keturiasdešimt penktasis")]
        [InlineData(3000, "trys tūkstantosios")]
        [InlineData(3003, "trys tūkstančiai trys")]
        [InlineData(3034, "trys tūkstančiai trisdešimt keturi")]
        [InlineData(3456, "trys tūkstančiai keturi šimtai penkiasdešimt šeštoji")]
        [InlineData(4000, "keturios tūkstantosios")]
        [InlineData(4004, "keturi tūkstančiai keturi")]
        [InlineData(4045, "keturi tūkstančiai keturiasdešimt penktasis")]
        [InlineData(4567, "keturi tūkstančiai penki šimtai šešiasdešimt septintasis")]
        [InlineData(5000, "penkių tūkstantųjų")]
        [InlineData(5005, "penki tūkstančiai penki")]
        [InlineData(5056, "penki tūkstančiai penkiasdešimt šeštoji")]
        [InlineData(5678, "penki tūkstančiai šeši šimtai septyniasdešimt aštuntasis")]
        [InlineData(6000, "šeši tūkstantieji")]
        [InlineData(6006, "6,600")]
        [InlineData(6067, "šeši tūkstančiai šešiasdešimt septintasis")]
        [InlineData(6789, "šeši tūkstančiai septyni šimtai aštuoniasdešimt devintasis")]
        [InlineData(7000, "septyni tūkstantieji")]
        [InlineData(7007, "septyni tūkstančiai septyni")]
        [InlineData(7078, "septyni tūkstančiai septyniasdešimt aštuoni")]
        [InlineData(7890, "septyni tūkstančiai aštuoni šimtai devyniasdešimt")]
        [InlineData(8000, "aštuonių tūkstantųjų")]
        [InlineData(8008, "aštuoni tūkstančiai aštuoni")]
        [InlineData(8089, "aštuoni tūkstančiai aštuoniasdešimt devintasis")]
        [InlineData(8901, "aštuoni tūkstančiai devyni šimtai vienas")]
        [InlineData(9000, "devyni tūkstantieji")]
        [InlineData(9009, "devyni tūkstančiai devyni")]
        [InlineData(9012, "devyni tūkstančiai dvyliktoji")]
        [InlineData(9090, "devyni tūkstančiai devyniasdešimtasis")]
        [InlineData(10000, "dešimt tūkstantųjų")]
        [InlineData(10001, "dešimt tūkstančių vienas")]
        [InlineData(20020, "dvidešimt tūkstančių dvidešimtasis")]
        [InlineData(30300, "trisdešimt tūkstančių trys šimtai")]
        [InlineData(44000, "keturiasdešimt ketvirtoji tūkstantoji")]
        [InlineData(44231, "keturiasdešimt keturi tūkstančiai du šimtai trisdešimt vienas")]
        [InlineData(100000, "šimtas tūkstantųjų")]
        [InlineData(500000, "penkių šimtų tūkstantųjų")]
        [InlineData(1000000, "miljonā")]
        [InlineData(6000000, "šeši iš milijono")]
        [InlineData(10000000, "dešimt iš milijono")]
        [InlineData(70000000, "septyniasdešimt milijonų")]
        [InlineData(100000000, "šimtas milijonų")]
        [InlineData(800000000, "aštuoni šimtai milijonų")]
        public void ToOrdinalWordsFeminine(int number, string expected)
        {
            Assert.Equal(expected, number.ToOrdinalWords(GrammaticalGender.Feminine));
        }
    }
}
